//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Departments
{
    public Departments()
    {
        this.Users = new HashSet<Users>();
    }

    public int DepartmentID { get; set; }
    public string Name { get; set; }
    public int FacultyID { get; set; }

    public virtual Faculties Faculties { get; set; }
    public virtual ICollection<Users> Users { get; set; }
}

public partial class Faculties
{
    public Faculties()
    {
        this.Departments = new HashSet<Departments>();
        this.Users = new HashSet<Users>();
    }

    public int FacultyID { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Departments> Departments { get; set; }
    public virtual ICollection<Users> Users { get; set; }
}

public partial class SubTopics
{
    public SubTopics()
    {
        this.Videos = new HashSet<Videos>();
    }

    public int SubTopicID { get; set; }
    public int MainTopicID { get; set; }
    public string SubTopic { get; set; }

    public virtual Topics Topics { get; set; }
    public virtual ICollection<Videos> Videos { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class Topics
{
    public Topics()
    {
        this.SubTopics = new HashSet<SubTopics>();
        this.Videos = new HashSet<Videos>();
    }

    public int TopicID { get; set; }
    public string Title { get; set; }

    public virtual ICollection<SubTopics> SubTopics { get; set; }
    public virtual ICollection<Videos> Videos { get; set; }
}

public partial class Users
{
    public Users()
    {
        this.Videos = new HashSet<Videos>();
    }

    public int UserID { get; set; }
    public string Password { get; set; }
    public string Name { get; set; }
    public string Surname { get; set; }
    public string Email { get; set; }
    public int FacultyID { get; set; }
    public int DepartmentID { get; set; }
    public bool IsActive { get; set; }
    public bool IsAdmin { get; set; }
    public bool IsApproved { get; set; }
    public int UserType { get; set; }
    public string Photo { get; set; }
    public string Phone { get; set; }

    public virtual Departments Departments { get; set; }
    public virtual Faculties Faculties { get; set; }
    public virtual ICollection<Videos> Videos { get; set; }
}

public partial class Videos
{
    public int VideoID { get; set; }
    public string Title { get; set; }
    public int UserID { get; set; }
    public System.DateTime UploadDate { get; set; }
    public string Path { get; set; }
    public int TopicID { get; set; }
    public int SubTopicID { get; set; }

    public virtual SubTopics SubTopics { get; set; }
    public virtual Topics Topics { get; set; }
    public virtual Users Users { get; set; }
}
