//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class CuriousCamEntities : DbContext
{
    public CuriousCamEntities()
        : base("name=CuriousCamEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Departments> Departments { get; set; }
    public DbSet<Faculties> Faculties { get; set; }
    public DbSet<SubTopics> SubTopics { get; set; }
    public DbSet<sysdiagrams> sysdiagrams { get; set; }
    public DbSet<Topics> Topics { get; set; }
    public DbSet<Users> Users { get; set; }
    public DbSet<Videos> Videos { get; set; }
}
